// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package postgres

var TableNames = struct {
	AuthToken string
	User      string
}{
	AuthToken: "auth_token",
	User:      "user",
}
