// Code generated by SQLBoiler 4.3.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package postgres

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AuthTokens", testAuthTokensUpsert)

	t.Run("Users", testUsersUpsert)
}
