version: "2"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/partyzanex/go-admin-bootstrap
linters:
  default: none
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - mnd
          - noctx
          - gosec
          - err113
          - goconst
          - gocritic
          - unparam
          - wsl_v5
          - funlen
          - dupl
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - err113
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - lll
    - misspell
    - mnd
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/sirupsen/logrus"
              desc: "use log/slog instead"
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G101
        - G204
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

